// <auto-generated />
using System;
using CoDodoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoDodoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921213758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CoDodoApi.Entities.Opportunity", b =>
                {
                    b.Property<string>("UriForAssignment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HourlyRateInSEK")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameOfSalesLead")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UriForAssignment");

                    b.ToTable("Opportunity");
                });

            modelBuilder.Entity("CoDodoApi.Entities.Process", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FK_OpportunityUriForAssignment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FK_OpportunityUriForAssignment");

                    b.HasIndex("Name", "FK_OpportunityUriForAssignment")
                        .IsUnique();

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("CoDodoApi.Entities.Process", b =>
                {
                    b.HasOne("CoDodoApi.Entities.Opportunity", "Opportunity")
                        .WithMany()
                        .HasForeignKey("FK_OpportunityUriForAssignment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });
#pragma warning restore 612, 618
        }
    }
}
